### ISSUE TITLE
Config using System.env binds a compile time

### ISSUE THREAD

**Issue by smpallen99** [mustafaturan/shield#20]
First let me say that I have made this error in the past :)

The way you suggest using `System.env(...)` for configuration will not work as I believe you intend it to work. I'm referring to this part of the README file.

```elixir
config :shield_notifier,
  channels: %{
    email: %{
      from: {
        System.get_env("APP_NAME") || "Shield Notifier",
        System.get_env("APP_FROM_EMAIL") || "no-reply@localhost"}
    }
  }
```

If you want to support this application getting its config at runtime, you should do something like:

```
from: {
  {:system, "APP_NAME", "Shield Notifier"},
  {:system, "APP_FROM_EMAIL",  "no-reply@localhost"}
}
```

Then you need to add run time support for the tuple:

```
  def get_env_item({:system, name, default}) do
    System.get_env(name) || default
  end 
  def get_env_item(item), do: item
```

**Comment by mustafaturan** [comment]
Thanks for reporting @smpallen99,
I will be fixing it in asap.

**Comment by smpallen99** [comment]
@mustafaturan I did the same thing originally with Coherence. Had to spend a bit of time trying to figure out why my config was sometimes correct and other times it was not. :)
