### ISSUE TITLE
Example facebook and google

### ISSUE THREAD

**Issue by mbenatti** [mustafaturan/shield#28]
Hi,

There are some examples using shield to log'in with facebook and google using oauth2?

**Comment by gmile** [comment]
Hi @mbenatti!

`shield` is a oAuth2 microservice, e.g. a software that manages oAuth2 tokens, just like Google and Facebook.

Provided that, I believe your question is not valid. What you are looking for is client library, that'd handle facebook/google oAuth2 flow for you. For that you might want to take a look at https://github.com/ueberauth/ organization, among others they have these two repos:

* https://github.com/ueberauth/ueberauth_facebook
* https://github.com/ueberauth/ueberauth_google
