### ISSUE TITLE
A few problems with the library

### ISSUE THREAD

**Issue by darthrevan** [mustafaturan/shield#34]
We are currently trying to use the library to implement oAuth in our application

Here is the sample app that we've created to report the issue:
https://github.com/nbondarenko/sample_oauth

We need to add custom fields to User model.
The doc says that we should either
a) Override
b) Implement own model and add it into configuration file.

a) Override
Here is the sample app that we've created to report the issue:
https://github.com/nbondarenko/sample_oauth
We've run mix shield.install to create override classes
We've added a "test" field for user model and run the migration. Database shows that the field is present, and we were able to successfully create a model by using console 
http://localhost:4000/users/me works correctly in this case

However signing up through http://localhost:4000/users/register successfully creates a model and raises the error while rendering: https://monosnap.com/file/haxopxWVplXcynDVSV5fKGSvZVukEx

Apparently the library is trying to use original model while rendering, not the one that we are trying to override (so the :test field is missing).

b) By implementing our own model (which would be preferable) we are getting this:
https://gist.github.com/nbondarenko/943523d79f05b981a14c265cae3970a5

Sorry, we are new to Elixir/Phoenix stack. Could you please provide tips on how to make it work?

Thank you in advance!

**Comment by mustafaturan** [comment]
Hi @darthrevan ,

You also need to update migration file which located at the folder: `priv/repo/migrations`(you need to run migrations from scratch) OR you can create a new migration file using mix tool and add your new fields.

https://hexdocs.pm/ecto/Mix.Tasks.Ecto.Gen.Migration.html

Hope it helps.

**Comment by nbondarenko** [comment]
Hi! You can check our migration for creating user here https://github.com/nbondarenko/sample_oauth/blob/master/priv/repo/migrations/20160503214613_create_user.exs#L11. Migrations were run using `mix ecto.migrate` command.

**Comment by mustafaturan** [comment]
Oh I see, you should rename the module from `Authable.Model.User` to a name like `SomeOther.User`. Then you need to change config to:

```
config :authable,
  ...
  resource_owner: SomeOther.User,
  ...
```

**Comment by darklrd** [comment]
Upon changing `Authable.Model.User` to `SomeOther.User` the shield library throws the following error:

```
==> shield
Compiling 38 files (.ex)

== Compilation error on file lib/shield/policies/user/register.ex ==
** (CompileError) lib/shield/policies/user/register.ex:21: SomeOther.User.__struct__/1 is undefined, cannot expand struct SomeOther.User
    (stdlib) lists.erl:1354: :lists.mapfoldl/3

could not compile dependency :shield, "mix compile" failed. You can recompile this dependency with "mix deps.compile shield", update it with "mix deps.update shield" or clean it with "mix deps.clean shield"
```

Any suggestions as to what could be the issue?

**Comment by mustafaturan** [comment]
@darklrd 
If you need to use `SomeOther` as an alternative model, then `shield` needs to start after your `SomeOther` project.

**Comment by mustafaturan** [comment]
`@` caches on compile time, as an alternative to what I wrote above, you create a pull request to move `@` methods to functions. Then I can merge it.

**Comment by darklrd** [comment]
@mustafaturan Thank you for the quick reply.

If I try to replace `@` methods to functions, then I get the following error:

```
==> shield
Compiling 17 files (.ex)

== Compilation error on file lib/shield/policies/user/login.ex ==
** (CompileError) lib/shield/policies/user/login.ex:89: expected struct name to be a compile time atom or alias, got: get_token_store()
```

It seems like struct name has to be defined during compile time only. So it seems like it is not possible to replace compile time cached names by functions. Any suggestions?

On a side note, how do I run `shield` after my `SomeOther` project?

**Comment by mustafaturan** [comment]
You can set an order in your `mix.exs`

```elixir
  def application do
    [extra_applications: [..., :some_other, :authable, :shield, ...],
     mod: {Awsome.Application, []}]
  end
```

**Comment by szsoppa** [comment]
It appears this solution doesn't work either. I created example repo to reproduce this issue: https://github.com/szsoppa/deps_issue.

**Comment by albertchan** [comment]
I'm running into the same issue. Do we have a solution for this yet? Would greatly appreciate some pointers, thanks!

```
== Compilation error in file lib/shield/policies/user/register.ex ==
** (CompileError) lib/shield/policies/user/register.ex:21: AuthServices.Accounts.User.__struct__/1 is undefined, cannot expand struct AuthServices.Accounts.User
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    lib/shield/policies/user/register.ex:20: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```
