### ISSUE TITLE
mix shield.install in umbrella projects

### ISSUE THREAD

**Issue by raif-s-naffah** [mustafaturan/shield#36]
when **Shield** is a dependency of an application in an _Umbrella_ project, the invocation of the mix task in (the second) step 5 of Installation/As Package fails claiming inability to locate 'app_controller.ex'.

there must be a more elegant way of fixing this than changing './deps/...' in ines 60..63 to '../../deps/...' which works.

**Comment by mustafaturan** [comment]
@raif-s-naffah waiting for your PR, feel free to contribute with tests
