### ISSUE TITLE
RFC7662 (Token Introspection) support

### ISSUE THREAD

**Issue by raarts** [mustafaturan/shield#37]
For a good summary of this, see this quora answer: [In OAuth 2.0, how do resource servers assert a token issued by an authorization server?](https://www.quora.com/In-OAuth-2-0-how-do-resource-servers-assert-a-token-issued-by-an-authorization-server)

**Comment by mustafaturan** [comment]
Hi @raarts ,

It looks very usefull, thanks for reporting. The `shield` package will cover this spec (https://tools.ietf.org/html/rfc7662).

**Comment by mustafaturan** [comment]
For now, you can consume smilar appraoch:
```
get     "/tokens/:id", TokenController, :show
```

**Comment by mustafaturan** [comment]
it seems the token show endpoint covers this.

```elixir
get     "/tokens/:id", TokenController, :show
```
