### ISSUE TITLE
Not able to make a hooks work

### ISSUE THREAD

**Issue by gmile** [mustafaturan/shield#39]
After installing `shield` as a dependency I'm trying to make hooks work.

I have my own hook module that look like this:

```elixir
defmodule MyHooks do
  def after_user_login_success(conn, data) do
    IO.inspect data, label: "--- testing ---"

    conn
  end

  use Shield.Hook
end
```

The config points to my hook module:

```elixir
use Mix.Config

config :shield,
  # ...
  hooks: MyHooks
```

However my hook is not being picked up.

One thing to note here is that during my own app's boot I get a warning related to `shield` app:

```
iex -S mix phx.server
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Compiling 26 files (.ex)
warning: this clause cannot match because a previous clause at line 2 always matches
  lib/trump_api/hooks.ex:10

Generated my_app app
warning: no configuration found for otp_app :shield and module Shield.Endpoint
[info] Running MyApp.Web.Endpoint with Cowboy using http://0.0.0.0:4000
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```
I think I'm missing something obvious, configuration-related. But I can't understand what is it. I'll try to prepare a demo repo tomorrow.

**Comment by mustafaturan** [comment]
In first look, I saw you did not put default hooks on top. I think this will solve the problem, if it does not I need to the project. 

```elixir
defmodule MyHooks do
  use Shield.Hook # moved to top

  def after_user_login_success(conn, {_params, %{"user" => user}}) do
    Logger.log(:debug, fn  -> inspect(user) end)
    ...
    conn
  end

end
```

**Comment by mustafaturan** [comment]
@gmile is that solved the problem?

**Comment by gmile** [comment]
I was not able to look into it further. But last time I tried it was not
resolved, no.

**Comment by mustafaturan** [comment]
Could you please push it in a gist or GitHub repo link? The configuration I posted, should work.
