### ISSUE TITLE
/login /logout for Authable.GrantType.Password

### ISSUE THREAD

**Issue by pragmaticivan** [mustafaturan/shield#40]
Hi there, not sure if there's a better place to ask questions.

Currently, the `/login` and `/logout` just work with session_token which means it uses "cookies".

Also for login, you don't really need to specify client_id and secret for instance.

I was playing with the endpoint POST /tokens

```
# fake request
curl -X "POST" "http://tenant.myapp.dev:4000/v1/tokens" \
     -H "Content-Type: application/json" \
     -d $'{
  "token": {
    "client_id": "86dc2c41-a2fd-4209-910d-b089j42594af2",
    "client_secret": "K2ZNV444MldicnZ501RhdEJlZjJDQT09",
    "email": "user@domain.com",
    "password": "password",
    "grant_type": "password"
  }
}'
```

So, that creates an `access_token` which doesn't create a state with cookies.
So, I'm wondering if that was the purpose of shield to not have a way to revoke an access_token, and instead, just have a way to revoke a session_token.

**Comment by mustafaturan** [comment]
@pragmaticivan 
`/login` and `/logout` endpoints are not part of oauth2 spec but the `/tokens` endpoint is.

**Comment by pragmaticivan** [comment]
So, no plans for https://tools.ietf.org/html/rfc7009 ?

**Comment by mustafaturan** [comment]
Currently only `rfc6749`
