### ISSUE TITLE
Manually handling authentication

### ISSUE THREAD

**Issue by drozzy** [mustafaturan/shield#41]
Pardon my ignorance, I'm just starting to implement oauth2 server-side , but what does this example mean?

In particular, I'm not sure of:

- Where does the `authorize_for_resource` comes from?
- Why the return value is an IO.puts/inspect result?
- What is the `required_scopes` here and why is it "session"?

> Manually handling authentication:
> 
> defmodule SomeModule.AppController do
>   use SomeModule.Web, :controller
>   ...
>   import Authable.Helper
> 
>   def register(conn, _params) do
>     required_scopes = ~w(session)
>     case authorize_for_resource(conn, required_scopes) do
>       {:ok, current_user} -> IO.puts(current_user.email)
>       {:error, errors, _} -> IO.inspect(errors)
>       nil -> IO.puts("not authencated!")
>     end
>     ...
>   end
> end

**Comment by al3x-edge** [comment]
@drozzy 

- `authorize_for_resource` comes from `Authable.Helper` (https://hexdocs.pm/authable/Authable.Helper.html)
- The return value of Authable.Helpers looks to be a tuple of either {:ok, current_user} or {:errors, errors} which is pattern matched by the case statement. IO.puts / IO.inspect are being run from the case statement.
- Scopes here refer to OAuth scopes I believe which are created with the token?  Upon authorizing, the call is requiring that the use is allowed the session scope... I think.

**Comment by mustafaturan** [comment]
@al3x-edge 👍 

closing this one. All oauth2 helpers are coming from `authable` package.
