### ISSUE TITLE
Is it possible to use mongodb_ecto?

### ISSUE THREAD

**Issue by darklrd** [mustafaturan/shield#45]
Hello,

I am trying to replace Ecto.Adapters.Postgres with Mongo.Ecto but it doesn't seem to work. I keep getting this error:

```
== Compilation error on file lib/authable/repo.ex ==
** (ArgumentError) adapter Mongo.Ecto was not compiled, ensure it is correct and it is included as a project dependency
    lib/ecto/repo/supervisor.ex:55: Ecto.Repo.Supervisor.compile_config/2
    lib/authable/repo.ex:6: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

Is it possible to use Mongo instead of Postgres?

Thanks

**Comment by mustafaturan** [comment]
Sorry, it is not possible for now. Because shield currently depends on authable library which comes with posgrex
