### ISSUE TITLE
Confirm registration after token expiration

### ISSUE THREAD

**Issue by DrunkenInfant** [mustafaturan/shield#55]
Hi,

I can't seem to find a way to send a new confirmation email to the user if the user fails to confirm its email within one hour (hardcoded expiration). Has there been a thought as to how this is flow is supposed to be implemented? Should there be something cleaning up the database regularly to allow unconfirmed emails to be reused?

I have never encountered this problem when registering myself on various services. Is there a reason for the one hour expiration? I've tried to find any relevant papers or discussions on the topic without success, why is the expiration needed? To me it seems like this does not have any security implications as the token only confirms the recipient of the email, not necessarily the user, received the token.

Any thoughts?

**Comment by mustafaturan** [comment]
Hi @DrunkenInfant 

You can change token expiration time, by an after registration hook. 

And your use case is not supported by `shield`, you need to implement this functionality manually.
