### ISSUE TITLE
State of OpenID Connect support?

### ISSUE THREAD

**Issue by raarts** [mustafaturan/shield#58]
This library is [listed](http://openid.net/developers/uncertified/) as 'Uncertified OpenID Connect Implementation'. According to the open site this means: "_they are maintained by members of the OpenID community or vendors and are not necessarily known to work._".
The Swagger documentation does not show anything OpenID related that I can find. 

Was listing this package on the OpenID site premature? 

As an aside, is this package still being maintained?

**Comment by mustafaturan** [comment]
OpenID support is only on `ui` branch
