### ISSUE TITLE
Updating dependencies and v0.9.1 of authable

### ISSUE THREAD

**Issue by kerryjj** [mustafaturan/shield#59]
Hi,

I tried to create a fork with these updated dependencies.
```
{:phoenix, "~> 1.2.5"},
{:authable, "~> 0.9.1"},
{:cors_plug, "~> 1.2.1"},
```

However, it looks like Authable.Repo doesn't exist in the v0.9.1 of authable and instead there's an Authable.RepoBase.  Is there an example of use of Authable.RepoBase somewhere I can see to figure out how to use this version?

**Comment by mustafaturan** [comment]
master branch of `shield` is compatible with `{:authable, "~> 0.8.0"}`
