### ISSUE TITLE
Did you have plan to support for mongodb?

### ISSUE THREAD

**Issue by kevinblade** [mustafaturan/shield#9]
Hi!
I have used for doorkeeper for oauth2 provider in previous project.
As you know which is great gem for API authentication & authorization in Rails environment.
Also that supports mongodb, so, I have experimentally tried mongodb with your shield but I am failed.
Because mongodb_ecto doesn't fully support latest ecto but your shield needs it. How do you think about this issue.
Let me know about your plan for supporting mongodb.

Cheers.

**Comment by mustafaturan** [comment]
No plan until v1
